name: Update Gradle Wrapper

on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch: 

jobs:
  update-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: true 

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          check-latest: true

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle wrapper task
        run: ./gradlew wrapper --gradle-version 8.13 

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradle/wrapper/* gradlew gradlew.bat
          git diff --quiet || git commit -m "chore: update Gradle wrapper"
          git push
